### ISSUE TITLE
[Suggestion] Bounty Expired Notification

### ISSUE THREAD

**Issue by abboip** [ejektaflex/Bountiful#10]
Currently, bounties disappear from the player's inventory when they expire. To give the player more feedback on the expiration of bounties, I would like to suggest a chat message for that player saying their bounty expired. Perhaps mousing over the message would display the specifics of the bounty a la mousing over an advancement.

In addition, a one minute-five minute warning message might also be an idea in itself. Though I can see why you want to promote players paying attention to the bounties as their top priority when they pick them up.

**Comment by ejektaflex** [comment]
That's a great idea. I'm actually going to add that to the tooltip of the bounty, so if it has expired, it will show "Expired" in red instead of telling you the time, as mentioned in #6. Doing so actually solves some other problems as mentioned there.

Right now, the amount of time on the bounty is a pretty good indicator that I want the player's priority to be working on the bounty - it has to be enough time for them to get the materials, but not too little that they will *only* take the bounty if they have the items *already*. I may implement a one minute warning message, though if I do it will only go off if the bounty is in the player's inventory

**Comment by abboip** [comment]
Interesting! I agree, I think that would solve a lot of issues.

I realize it might be a bit of work just for a config option, but while we're on the topic of the expiry time: perhaps an option for a "hard mode" where the timers start counting down when they're posted on the board? (With maybe an additional couple minutes to offset the common bounties with short deadlines.) This could give pack makers the power to curb cheesing them by getting everything beforehand, but it might be a bit much for default play. (And not what you envisioned, which is important!)

**Comment by ejektaflex** [comment]
That's a good idea, I can do that fairly easily. I'll add that to my list!

**Comment by ejektaflex** [comment]
Both of these have been implemented as of 8014740, also closing #6 . Config now allows timer to start countdown immediately as it's posted, and bounties can now still expire when placed inside of other objects.
