### ISSUE TITLE
[Question] Is there any way to only ask for specific NBT data in Objectives?

### ISSUE THREAD

**Issue by Kayatwo** [ejektaflex/Bountiful#115]
So these past couple of days I've been trying to make my own data pack while including as many mods as possible from my mod pack. 
I've also tried adding in mob cages from the Supplementaries mod as objectives for the hunting decree. However, due to these cages copying the specific NBT data of the caged mob, I can't create a generalized objective for them.
So, I was wondering whether there was any way to only check a specific attribute while ignoring the rest or ignore the NBT data entirely.
I presume this is probably not possible but I figured I'd ask anyway.

**Comment by ejektaflex** [comment]
I believe that cashing in bounties always does an NBT check on every item and compares it to the NBT of the item in the bounty (and you can specify custom NBT data, [as shown here](https://github.com/ejektaflex/Bountiful/wiki/1.12-Customizing-Bounties)).

For Bountiful v5 (which will be released for Fabric), I shall consider adding a wildcard option so that it doesn't have to match NBT tags when turning items in!
