### ISSUE TITLE
Bug/Crash

### ISSUE THREAD

**Issue by krisxd** [ejektaflex/Bountiful#117]
So i have not seen anyone bring this up lately, but atleast for me and couple of other people, when you hover the mouse on the item Degree, it instantly crashes the game.
I don't think you need logs because there were some posts about this that had them.
Anyone know a fix or is there a mod that interrupts something ?

**Comment by ejektaflex** [comment]
I do actually need logs - otherwise I don't know what the error is. The tooltip calculates several things and the crash could be happening at any step of the process :^)

Where'd you get the decree from, did it spawn in the board?

As per the issue request, please add a crash log as well as the version of Minecraft, Forge and Bountiful!
