### ISSUE TITLE
Min/Max option for amount of mob kills not working properly

### ISSUE THREAD

**Issue by InmoNum** [ejektaflex/Bountiful#121]
So I've been playing in 1.16 with the datapack.. As can be seen from the comments on curse page xD
But! I've come across a problem because all the decrees I've added are working, but pools for mob hunting and such are not working properly!

The "amountRange" min/max option is not picking between min and max but instead only choosing the min number.
Any way to fix this? :/
![Capture](https://user-images.githubusercontent.com/79522136/108853770-69ed8100-75e7-11eb-897c-e81e4e23b85d.PNG)

Here's the code:

    "content": [
      {
        "type": "entity",
        "content": "pandoras_creatures:arachnon",
        "amountRange": {
          "min": 1,
          "max": 5
        },
        "unitWorth": 700,
        "weight": 1000
      }

**Comment by ejektaflex** [comment]
Yes - the algorithm will try to find any valid objectives that fit your current rewards. If you're only seeing 1 of the objectives, you need to make your rewards worth more value or add more objectives and rewards. What does the JSON data look like for combat experience?

Archvine kills are worth 700 each, so you need to be offering at least around 1400 in rewards in order to even start seeing two Archvine kills as an objective!

Alternatively, adding more cheap objectives may also balance out the equation. In general, it tries to balance out objective cost with reward cost but this is a situation where it can't do so, as the values on each side won't match up well.

**Comment by InmoNum** [comment]
OHHH!!!! That makes sense xDD
![Capture](https://user-images.githubusercontent.com/79522136/109172801-73abeb80-7783-11eb-9407-94d0e140128d.PNG)
That's the rewards!
the reward is pretty much a PMMO mod experience :)
Also does It look at unit worth or weight in the rewards?

**Comment by ejektaflex** [comment]
Hey, it's neat to see somebody using the command rewards! Sweet! It looks at weight only to determine how often the reward shows up - but yes, it always looks at unit worth.

In your example, you may want to keep the unitWorth the same for all three objectives - because one unit of experience should be the same "worth" for all three objectives. 

But yeah, you should start to see multiple Archvine kills as an objective here. The minimum total value of any of these rewards is around 2000-2100, so it should try to find objectives that are roughly 2000-2100 in worth (plus or minus 20% ✨), which Archvines should fall into.

**Comment by InmoNum** [comment]
Yea! The command option is legit the life saver here hahaha,
It's perfect for a "MMORPG" kind of a modpack!

Also I don't know why I didn't think about keeping the unit worth the same and just changing the weight.. 
Thank you hahahah

**Comment by InmoNum** [comment]
So If I have unit worth of the Objective set to 500 and Unit worth of the reward set to 1000 I should start seeing more than 1 objectives right?
Or am I gathering this information wrong xD

**Comment by InmoNum** [comment]
So this is what I've set the unit worth to, first is the Objectives, second is rewards

      {
        "type": "entity",
        "content": "pandoras_creatures:arachnon",
        "amountRange": {
          "min": 1,
          "max": 32
        },
        "unitWorth": 225,
        "weight": 1000,
        "timeMult": 2.0
      }

Rewards

        {   
            "type": "command",
            "name": "Combat experience",
            "content": "/pmmo admin %player% add combat level %amount%",
            "amountRange": {
              "min": 1,
              "max": 10
            },
            "unitWorth": 1250,
            "weight": 800
        }

And still keep getting only the min number, Am I still doing it wrong? xD

**Comment by ejektaflex** [comment]
Is that all that's in your pool files? If so, that should be right. Any reward will be worth at least 1250, so it will try match you up with ~1250 worth of objectives, which would be 5-6 `pandoras_creatures:arachnon`.

**Comment by InmoNum** [comment]
Yep! I've removed everything just to make sure I'm not going crazy, but still kept making it only the min number of the amountRange part, When i Increased it to 2 all the bounties had 2 objectives instead of one

**Comment by ejektaflex** [comment]
If you could attach a zip file of the datapack, I'd be curious to look at it.
