### ISSUE TITLE
No Config in Forge Version?

### ISSUE THREAD

**Issue by ghost** [ejektaflex/Bountiful#123]
I'm running Bountiful-1.16.4-3.3.0.jar on Forge 1.16.5 and there is no config folder or config files generated. I'd like to tweak the rewards as the epic bounties are still only awarding stone tools and bonemeal. Is there another way to do that?

**Comment by ejektaflex** [comment]
A decent number of configs in Forge can be serverside only since 1.14 - and Bountiful's configs are all serverside only :^)

You can find the config for a world in `[world-name]/serverconfig/bountiful-server.toml`.

However, if you want to modify objectives and rewards, you will need a datapack. These resources can help you:
[Minecraft Wiki](https://minecraft.gamepedia.com/Data_Pack)
[Bountiful Wiki](https://github.com/ejektaflex/Bountiful/wiki)
[Bountiful Data Folder](https://github.com/ejektaflex/Bountiful/tree/develop/src/main/resources/data/bountiful)

Good Luck!
