### ISSUE TITLE
Gazebo not spawning with Farmer's Delight

### ISSUE THREAD

**Issue by Alcates** [ejektaflex/Bountiful#125]
## Bug Report

**Observed Behaviour**

What happened: Bounty boards and their associated gazebo structures are not spawning in any generated worlds. The console log is reporting "Couldn't parse loot table bountiful:blocks/bountyboard" upon world start, which I believe to be the issue.

Crash log: https://pastebin.com/aiFDauAt

**Expected Behaviour**

What should have happened: At least a few of the dozens of villages generated should have contained bounty board structures and the aforementioned error should not have appeared in the log.

**Minimal setup needed to reproduce**

- Forge version: 36.0.58
- Bountiful version: 3.3.1
- Other mods: It's a whole pack of ~115 mods and I haven't determined if one of them is to blame. Mod list may be provided upon request.

**Steps to reproduce**

How to recreate this:

1. Generate world
2. Locate village

**Comment by ejektaflex** [comment]
It's definitely not that, unfortunately, that error just shows up because I don't provide any Json ops for when bounty board loot drops.

Please generate a world and locate a village, then quit and provide a full log! It would be much appreciated :^) Then I can view the entire log for errors, as well as your mod list.

**Comment by Alcates** [comment]
[2021-03-24-2.log.gz](https://github.com/ejektaflex/Bountiful/files/6200989/2021-03-24-2.log.gz)
There's the full log. (Manually debug-crashed to generate the log file.)

[Race to Ascension-2.1.zip](https://github.com/ejektaflex/Bountiful/files/6200998/Race.to.Ascension-2.1.zip)
Here's the pack export.

**Comment by LuckiestRug** [comment]
i was having the same problem and i believe farmer's delight is the issue. removing the mod entirely seemed to make the gazeboes spawn again. although going into the config for farmer's delight and setting "cropsonvillagehouseloot" to false seemed to fix the issue for me. 


#World generation
[world]
	#Generate crop items on Village houses (all biomes)
	cropsOnVillageHouseLoot = false

**Comment by ejektaflex** [comment]
Ah, that might make some sense. Since I just insert into the existing village pools (the gazebo counts as a village "house") it may be best to report this on their issue tracker. It sounds like they might be making some assumptions about the houses, or trying to run some code that doesn't work on the gazebos.

**Comment by ejektaflex** [comment]
I'm going to close this, since it sounds like Farmer's Delight interfering with existing jigsaw pools.
