### ISSUE TITLE
[Suggestion] Global bountyboard

### ISSUE THREAD

**Issue by someaddons** [ejektaflex/Bountiful#129]
## Feature Request

**Feature description**

I think it'd be nice if there was an option to have the bounties be in a global pool, such that players don't simply spam 10-15 bounty boxes to get all they ever wanted. Could be world global/or even just global for the same chunk, that'd limit it a bit too.
I'd probably make the global inventory/pool save the bounties per decree, such that having different decrees still has an effect and changes which bounties are displayed to you. They could also affect the rate at which the global pool generates bounties, e.g. 3 decrees of the same thing -> (1-1/3) +1 = 1.7 multiplier for generation, which wouldnt scale up too much either.

Could even have village bounty boards be special ones, which have some special pool but are unbreakable.

**How it improves the player experience**

How this would make Bountiful better:

It removes that players just spam bounty boards, and instead want to frequently check in on the few they have. Also gives a nice social interaction element when one player takes one the other wanted.

**Comment by ejektaflex** [comment]
This used to be a thing, but I removed it in later versions. If you want to restrict the number of bounties the player can take at a time, you should disable crafting of bounty boards so that they can only be found in the world. You can then tweak the rate of bounty generation for all natural boards in the config.

As such, I don't see myself adding global board support again in the Forge version, given the amount of work vs how often it would be used (even if it would be nice, I agree!). It may happen again in Fabric, but not right away. I'd always accept a high quality pull request, though.

Also, something that I've learned that's related to your last sentence: In my experience, it's generally more fun if you find a neat bounty and you can share it with your friends. What's the harm in two people having their own copy of the same bounty? There really isn't any - instead, it actually incentivizes people to work towards the same goals together. In the Fabric version of the mod, I've made it so that all boards are "instanced" - so Player A taking Bounty X off the board only takes it off the board for Player A. Player B can still take Bounty X if they want. 

As a result, I've seen a lot of neat social interactions with this new system. "Hey, this bounty gives us 10 of X if we go kill some Zombies and find some Coal. Wanna do it together? You can grab your copy from the board and we can head off!"

I do really love the idea of multiple decrees of the same type increasing bounty frequency - that's a really good use case for collecting multiple of the same decree! Currently, duplicates are useless, which I've wanted to change (well, besides anvil combining. I'm not sure if I've mentioned it much anywhere, but you can combine decrees in an anvil using experience! Thus, you can store more than 3 types of decrees on a board at once.)

**Comment by ejektaflex** [comment]
In the newest version (1.19.4+), boards are instanced per board, with taken bounties being instanced per player (e.g. you will see the same bounties as your friends when looking at the same board, but that doesn't stop you from both taking the same bounty).
