### ISSUE TITLE
2.0 Server Crash

### ISSUE THREAD

**Issue by MokahTGS** [ejektaflex/Bountiful#13]
Got a crash with 2.0 on a dedicated server reloading the json with the commands.

https://pastebin.com/t6iJVdrP

**Comment by ejektaflex** [comment]
This means that your "bounties.json" contains fewer entries than the maximum number of things a bounty could ask you to get.

Example: if you changed the config so that it could ask you to get 1-3 different things, but there were only 2 entries in "bounties.json", you would get this error.

You need to add more bounties.

I will keep this is me open and catch it more gracefully in the next update, though!

**Comment by ejektaflex** [comment]
They *are* set up, so you should post the contents of the "bounties.json" here:
https://gist.github.com/
and send a link so that I can look at it.

**Comment by MokahTGS** [comment]
These are the jsons shipped with the mod, I didn't touch any of them.

Bounties json: https://pastebin.com/eGKw9t9L

Bountiful Config: https://pastebin.com/xdkD2sc9

Rewards json: https://pastebin.com/8A3Jkw3w

**Comment by MokahTGS** [comment]
so it seems to be a config mismatch.  I've deleted the old configs that were on the server and have let the 2.0 version generate new ones.  The reload command was tried because no bounties were showing up when the board was placed.  How long does it take to populate the board with bounties?

**Comment by ejektaflex** [comment]
The config determines how long it takes. The default time is, I believe 2400 ticks (20 ticks = 1 second), so 120 seconds, or two minutes.
