### ISSUE TITLE
Craft to Exile Dissonance

### ISSUE THREAD

**Issue by TronWoWGamer** [ejektaflex/Bountiful#140]
Right clicking on the bounty board doesn't turn in bounties.  It just opens the bounty board.  Also had this problem in other modpacks in both 1.12 and 1.14 modpacks.

**Comment by ejektaflex** [comment]
There's a template for new bug reports that needs to be followed before I can try to reproduce a bug. Please supply this data, and then I can look into it!

## Bug Report

**Observed Behaviour**

What happened:

Crash log: 

**Expected Behaviour**

What should have happened:

**Minimal setup needed to reproduce**

- Forge version: 
- Bountiful version: 
- Other mods:

**Steps to reproduce**

How to recreate this:
