### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by TalonsOfStealth** [ejektaflex/Bountiful#142]
I don't know exactly what causes this but I was playing with Bountiful and had my internet go out, I was on a server hosted from my own computer  and when I restarted my internet and tried to rejoin I got "Internal server error". I then looked it up and found another post like this saying that bountiful was causing it, I know you've already heard of this but I was hoping this could shed some light on what is causing this issue

**Comment by ejektaflex** [comment]
Maybe, I have no clue. It could be any number of mods in your mod list, unless proven otherwise. When you open a bug report, there's a template that you should use so that I can help you figure out what is wrong - since you've not chosen to use it, I'll copy and paste it here. I need this information before I can figure out whether the problem comes from Bountiful, and if so, how to fix it:

## Bug Report

**Observed Behaviour**

What happened:

Crash log: 

**Expected Behaviour**

What should have happened:

**Minimal setup needed to reproduce**

- Forge version: 
- Bountiful version: 
- Other mods:

**Steps to reproduce**

How to recreate this:



Once you supply that information, I can help you! Since this is running on a local server, it would be helpful to have both the client and server log results after trying to connect. Thank you! :^)
