### ISSUE TITLE
[1.16.5] Found what seems to be a bug with the .json of something in the log

### ISSUE THREAD

**Issue by vizthex123** [ejektaflex/Bountiful#143]
I found this section in latest.log, which seems to be cataloguing an error in the loading of a loot table:
https://gist.github.com/vizthex123/1d800a02aa9261008d9bb9eb1d4a6cf2

**Minimal setup needed to reproduce**

- Forge version: 36.2.2
- Bountiful version: 3.3.1

**Steps to reproduce**

How to recreate this: Load the game then check the log.

**Comment by ejektaflex** [comment]
The loot table parse failure is something I've never been able to quite figure out - this happens when breaking the bounty board. I'm not passing any operations to the MC function, but when I do, it doesn't work correctly. I've never found a fix for this despite searching for several hours, but it does not effect gameplay so I've left it as is. As such, I'm closing this as it's not an issue, but thank you for the report!
