### ISSUE TITLE
item-tag type objective entries display the tag (instead of an item name)

### ISSUE THREAD

**Issue by incfool** [ejektaflex/Bountiful#145]
### What happened?

Mostly a cosmetic issue - the bounties function just fine

![bo_tagissue](https://user-images.githubusercontent.com/79022219/130331620-1f2787e4-3579-42c2-9c00-7fb3f9fcfddd.png)

### Mod Version

3.3.1

### Forge Version

forge-36.2.0

**Comment by ejektaflex** [comment]
I didn't add this objective, though you are correct. Minecraft tags do not have localized names, so it's up to the modpack maker to create a name for the tag. However, I've not documented this feature because item tag bounties [do not work correctly](https://github.com/ejektaflex/Bountiful/blob/develop/CHANGELOG.md#removals) in this version.

You can attempt to add your own name for the objective by following the example [here.](https://github.com/ejektaflex/Bountiful/blob/master/src/main/resources/data/bountiful/bounties/pools/bountiful/shepherd_objs.json#L5). Do note that this is not a localization key but instead a hard-coded text that is shown to players regardless of localization.

I still do not advise you use item tag bounties because they've not been fully reimplemented. Which modpack is this?

Thanks! :^)

**Comment by incfool** [comment]
Sorry - didn't see that in the changelog.  Yes, it's a custom pack/datapack, attempting to fix people trying to submit the "wrong" version of an item.  I'll make it more difficult to obtain the alternate versions instead.  Thanks for the response!

**Comment by ejektaflex** [comment]
It's alright, I wish it weren't so! Item tag bounties have a few problems right now that I'm ironing out in the Fabric version of the mod before I attempt to fix it here.

Thank you for your patience :^)
