### ISSUE TITLE
[Feature]: Backport basic bounty rarity gating to 1.12.2

### ISSUE THREAD

**Issue by leumas1960** [ejektaflex/Bountiful#146]
### Feature Description

I have a 1.12.2 modpack with the bountiful mod, and I went to make some custom bounties, but immediately realized you can't really control if rare items appear in common bounties or not! So, since that really breaks any more complicated usage of the mod, I was thinking a basic backport (not backport necessarily) adding a line to gate rewards/objectives with a simple line in each json file to whitelist different bounty rarities.

Just a simple line like so (for a common item):

"rarity": {"common": "100",
              "uncommon": "30"
            }
Would make the reward/bounty show up often in common bounties, occasionally in uncommon bounties, and never in unlisted tiers. Leaving out the line allows it in all tiers.

### Feature Benefits

Massive upgrade to functionality for simple addition. Old version, but many modpacks still use 1.12.2 currently.

**Comment by ejektaflex** [comment]
Unfortunately, I only do critical bug fixes for 1.12 (as mentioned in [the readme](https://github.com/ejektaflex/Bountiful)). Minecraft 1.12 is four years old, and many features are a pain to backport. I'm putting all of my time and energy (of which I don't have much) into the 1.17 version of Bountiful for Fabric.

Even if I did backport this feature, it actually would not be a backport. "Rarity" in 1.12/1.14/1.15/1.16 only determines how good of a deal you get in the bounty itself, not how often things show up. This hasn't been changed until the 1.17 version for Fabric, where it actually does what you think it should do.

Don't get me wrong - it would be nice to see this addition. But I work on this project because it's fun, and modding for 1.12 is not fun anymore :^) Anyone else is free to contribute the code needed to make this work, but 1.12 is a very, very rough draft of what is the 1.14+ version of the mod and has a lot of other problems as well.
