### ISSUE TITLE
Bounty Boards extremely rare[Bug]: 

### ISSUE THREAD

**Issue by Avalonzo** [ejektaflex/Bountiful#151]
### What happened?

I have be playing the better minecraft [PLUS] modpack and have noticed after creating/playing a new world for the latest update there were no bounty boards spawning. I then created a few test worlds and changed the spawn rate from 2 to 4 and doubling it each new world and making sure to create the world then to exit then change the rate. I eventually got to spawn rate 16 and saw 1 bounty board out  of the 10 villages I found.

### How can we reproduce it?

upon furthering testing via backdating to a separate instance of version 20.5 of the modpack bounty boards will spawn but not after updating the pack to version 21 the problem still persists in version 23.5. Which is the version I noticed it and reported it pack admins.

### Mod Version

1.16.4-3.3.1

### Forge Version

1.16.5/36.2.4

### Relevant log output

all relevant logs from logs folder -

[latest.log](https://github.com/ejektaflex/Bountiful/files/7244003/latest.log)

**Comment by Avalonzo** [comment]
Upon further testing managed to get a bounty board to appear once in 3 out of 10 villages with a max spawn rate of 16 and turning down the spawn rate of ice and fire mods scribe building which was over spawning some villages had 3+ of them. 2 out of 3 villages to have bounty boards were vanilla biomes a desert and a plains and the 3rd was a modded biome shrublands.

**Comment by ejektaflex** [comment]
Sounds like when a lot of other mods add buildings to villages, then the rate at which boards show up in villages goes down because it gets picked from a pool just as randomly as other mod's village buildings. That is to say, if for example the number of other possible village houses increased fourfold (4x), then you would be seeing bounty boards less than 1/4 as often, since it's odds of being picked as *the* house on a specific plot of land go down a lot.

Unfortunately, there's not much I can do about this besides insist that the modpack maker increase the board's generation frequency to account for other mods adding their own buildings.
