### ISSUE TITLE
[Bug]: Hexxit 1.2 Mac Compatibility Error with Bountiful

### ISSUE THREAD

**Issue by btparrish** [ejektaflex/Bountiful#159]
### What happened?

![image](https://user-images.githubusercontent.com/82351654/145664723-233be186-fce4-49d2-bdc0-35cdd0aa9063.png)

Bountiful causes Hexxit 1.20 to crash upon start. 

### How can we reproduce it?

Run Hexxit 1.20 with bountiful.

### Mod Version

2.2.2

### Forge Version

1.9.28

**Comment by ejektaflex** [comment]
I'm not going to download Hexxit to figure this out. You'll need to provide a log, just like the issue form requested.

Even that screen there gives you a link to the log, which is what I need to figure out what the crash actually was... :^)

**Comment by btparrish** [comment]
@ejektaflex sorry -- attached please find the error report for the crash that occurs in Hexxit 1.20 on Mac.
[crash-2021-12-11-22.04.23-client.txt](https://github.com/ejektaflex/Bountiful/files/7698115/crash-2021-12-11-22.04.23-client.txt)

**Comment by ejektaflex** [comment]
Thanks! The error lines shows this:
`Caused by: java.lang.Exception: 'bountiful/rewards.json' contains one or more invalid rewards. Invalid rewards: [PickedEntry (Stack) [Item: cqrepoured:feather_golden, Amount: 40, NBT: null, Weight: 40, Stages: null]]`

It looks like in your rewards.json file you have an invalid reward (`cqrepoured:feather_golden`). It's probably because that item does not exist (the mod was perhaps removed?). Removing that entry will probably fix the error!

**Comment by btparrish** [comment]
how can i go in and remove that? sorry -- not a java programmer and not super into minecraft mod writing! thanks so much for your help!

**Comment by ejektaflex** [comment]
Sorry for the delay - you have to remove the whole JSON object associated with that entry from config/bountiful/rewards.json. You can also run it through a JSON linter/validator to make sure the syntax is correct.

That's about as much as I can help you with it, so good luck! 😄
