### ISSUE TITLE
GameStages Support

### ISSUE THREAD

**Issue by NillerMedDild** [ejektaflex/Bountiful#16]
Hello!

I would like to suggest the ability to make certain bounties and rewards only become available to players with (or without) a specified GameStage. I'm thinking this would combine nicely with the upcoming CraftTweaker support, for maximum configurability :D

**Comment by ejektaflex** [comment]
I'll look at that for sure. I'm on the fence about CraftTweaker support now, since I offer the ability to hot reload the data from in-game. It could be a little useful, yes, but it does the exact same as what the config files do :thinking:

**Comment by NillerMedDild** [comment]
I can understand that, I could easily live without CraftTweaker support :)

**Comment by Nemerensis** [comment]
GS support would go a long ways towards keeping bounty boards fresh and exciting even into the late, late game!

**Comment by ejektaflex** [comment]
@Nemerensis I'm definitely considering it, along with The One Probe support. Currently, I'm working on a few other important features (like premade bounties as an option), but these will eventually make their way in. As more compat mods get added, though, development time slows down because each run takes longer to compile and start up!

**Comment by ejektaflex** [comment]
Finished as of 607ca9b. Will be in v2.2+.

The way it is currently implemented, each bounty and reward listing will have a "stages" key, with a string list associated with it. If you add this data, then that specific bounty/reward will be gated behind a specific gamestage. As long as one person on the server has all of the required game stages, that bounty/reward will show up on the bounty board (Although you personally must have all required stages unlocked in order to view the tooltip of the bounty!). 

Restrictions:

If, say, your config has it set so that bounties will always assign you 1-2 objectives, then you *must* have at least two bounty objectives that are *not* locked behind stages. Otherwise, it won't be able to produce a valid bounty.

Also, if it can't create a valid bounty (For any other reason, such as not having any valid rewards at the time to create a bounty), then it simply won't add any bounties to the bounty board.

**Comment by NillerMedDild** [comment]
Thank you! :D

**Comment by ejektaflex** [comment]
Any plans to add this to any modpacks @NillerMedDild? Just curious. I hope you enjoy the upcoming release. Whenever I have time, I will add examples to the wiki page showing all commands and the full json syntax.

**Comment by NillerMedDild** [comment]
Yep, it's in my new modpack Scientia, but it's still a long way from release.
It will most likely be going into any 1.13 / 1.14 pack I make aswell, if you decide to update :)

**Comment by ejektaflex** [comment]
Game Stages support has been added as of v2.2 on CurseForge, go check it out.

**Comment by NillerMedDild** [comment]
I know, thanks! :D
