### ISSUE TITLE
[Feature]: lower reward value deviation

### ISSUE THREAD

**Issue by AndMattBurt** [ejektaflex/Bountiful#170]
### Feature Description

a closer value comparison when generating rewards (to assist with a server economy)
we are seeing trades worth over 4million X input
![image](https://user-images.githubusercontent.com/43927299/154256269-36e4c50d-a1a4-48b3-a9d5-b80a7ed41075.png)
[lightmans_rews.zip](https://github.com/ejektaflex/Bountiful/files/8079489/lightmans_rews.zip)
[custom_objs.zip](https://github.com/ejektaflex/Bountiful/files/8079492/custom_objs.zip)
![Screenshot 2022-02-16 113348](https://user-images.githubusercontent.com/43927299/154256644-356439e3-ae88-4e21-8afa-f9b9799a268e.png)

### Feature Benefits

less outrageous rewards for items!

**Comment by AndMattBurt** [comment]
If there is something I am doing wrong (potentially with weighting) that would be helpful to add to the wiki

**Comment by ejektaflex** [comment]
In this version of Bountiful, value is different depending on rarity tier, making it so that less of the objective is needed to get the reward at higher rarity tiers.

This has been overhauled in Fabric, where we still try to do weight matching similarly, but do not factor in rarity tiers for purposes of value. 

To be honest, I never designed Bountiful to be used at such high values (though I'm happy to see people using it in creative ways! :^) ), so I didn't foresee the proportions being so far off. I'm guessing that you are using these as "quests" for late game automation. 

The solution would be to switch to how the Fabric version does their bounty calculations, though I unfortunately don't see that happening very soon. I don't have a ton of free time, and most of it goes into making the Fabric version better.

**Comment by ejektaflex** [comment]
1.19.4+ versions have a unified codebase between Fabric and Forge, which means this this is no longer a problem on newer versions of Bountiful (6.0.0+).
