### ISSUE TITLE
[Feature]: Partial reward completion

### ISSUE THREAD

**Issue by AndMattBurt** [ejektaflex/Bountiful#171]
### Feature Description

to be able to submit part of the reward so that you can have larger requests
(for use on a Train based modpack where moving large volumes is encouraged)

if the time expires in between drops then you lose any submitted items (maybe an alternative is better) (adds element of risk!)

### Feature Benefits

more customizability for a wider range of use cases/ more challenging in the late game

**Comment by ejektaflex** [comment]
As much as this would be nice, I think that there would be a huge number of upticks in complaints and frustration about losing stuff due to the mod, which I'd rather like to avoid.

There's also the fact that bigger random requests get very odd - a larger jumble of objectives makes the quests a lot less straightforward. I appreciate the idea, but I'm going to try to keep it simple where I can! :^)
