### ISSUE TITLE
Datapack setup

### ISSUE THREAD

**Issue by Marshmallow15** [ejektaflex/Bountiful#178]
### What happened?

hey I'm new to making datapacks and I wanted to mess around with your mods configs, but I'm not sure how much data I need to put into my datapack to change some basic stuff with your mod. Do I need to copy over each folder and file? I'm really just confused on how I'm supposed to set this up. I have a datapack setup I just need whatever amount of code to get started with making changes.

### Mod Version

1.16.5

### Forge Version

1.16.5

**Comment by ejektaflex** [comment]
What changes are you trying to make? Are you trying to add new items to pools?

**Comment by Marshmallow15** [comment]
yes all I want to do is change the objectives and rewards to fit the other mods I have, but to me I feel like it wouldn't work without every piece of code to the mod before I try to change anything.

**Comment by ejektaflex** [comment]
Hi - I've completely reworked how this works in 1.19.4+ in order to be more modular so that modpack authors don't have to overwrite large swathes of the original data in Bountiful. I'm going to close this case because it's a bit stale, but feel free to speak up in case it relates to how this new system works. You can find details here:

https://kambrik.ejekta.io/mods/bountiful/
