### ISSUE TITLE
[Bug]: Loading Bountiful listeners..

### ISSUE THREAD

**Issue by Varez971** [ejektaflex/Bountiful#182]
### What happened?

Hello, it has already happened several times that the server works correctly and when I go to play the next day, the server appears frozen with this message on the console: https://pastebin.com/rFubhZe8

Everything indicates that it is from the bountiful mod, but I don't know how to solve it.

### Mod Version

Bountiful-1.16.4-3.3.1.jar

### Forge Version

forge-36.2.35

**Comment by Blade1284** [comment]
Seems to be hit or miss whenever loading the server. I'm using the Better MC Plus 1.16.5 Modpack, and it looks like the startup process is similar to Varez's server, so it might be the same modpack. I'm able to stop/force kill and restart the server and have luck to continue.

[
![Bountiful json bug](https://user-images.githubusercontent.com/112715323/188183538-4513f247-d137-44ab-9867-961e75a5dea8.png)
](url)

**Comment by ejektaflex** [comment]
Hi there!
I've never seen this before, despite that version being a few years old. I would need some more information before considering this a Bountiful issue, as it has never come up before. Given that all of those mods are doing their loading in their own threads (note `modloading-worker-18`, `modloading-worker-25` etc) independently, it could be any of the mods loading at the same time as Bountiful that are doing this, if I recall correctly. I wouldn't say that anything here conclusively says that is a Bountiful issue, I'd need a bit more to go on in order to even start debugging this because it's not clear which mod is causing the problem.

**Comment by DemiRemi** [comment]
Having the same issue clientside. Using Better MC 1.16.5 on curseforge (Same version of mod, etc.) and it always freezes upon that same line. What information can I give to help find the actual problem?
[latest.log](https://github.com/ejektaflex/Bountiful/files/9718269/latest.log)

**Comment by ejektaflex** [comment]
Hi @DemiRemi , thanks for the log!

This is helpful, though it still doesn't seem to be a problem with Bountiful, from what I can tell. You're seemingly getting an error in Thread 44, which is not the thread that bountiful is working in (which is `modloading-worker-29`). All mods do their loading stage at the same time in different threads, so this still isn't definitively Bountiful instead of some other mod. Can you disable Bountiful and tell me whether this still happens?

Thanks!

**Comment by DemiRemi** [comment]
Still happens, so it must not be bountiful. Thanks for the help!

**Comment by ejektaflex** [comment]
That's what I thought - it's good to have it be confirmed. Thanks!
