### ISSUE TITLE
Free Decrees w/Inventory Sorting Mod

### ISSUE THREAD

**Issue by Lemuhi** [ejektaflex/Bountiful#199]
Hey there, 
I'm sure this is not intended, but I use the "Better minecraft" modpack for 1.18.1 fabric, and I have a sort inventory button...
This allows you to gain just about any decree you want from the bounty board as it will put the decree inside the same inventory as where the bounties are located, allowing you to transfer it to your own inventory.
If you choose to close the window and there is no decree in the decree slots, it will generate a new decree which means you can get all of them by just sorting inventory enough times.

Not sure what mod the sorting button comes from exactly, but this seems like an unintended conflict with that mod.

**Comment by ejektaflex** [comment]
Huh, that's a new one, thanks!

**Comment by ejektaflex** [comment]
If you could attach a mod list via a log or a screenshot or some such, that'd help a lot. :^)

**Comment by Lemuhi** [comment]
[2022-03-15-2.log.gz](https://github.com/ejektaflex/Bountiful-Fabric/files/8263193/2022-03-15-2.log.gz)
it is quite a few mods in that mod pack, but the mod itself that causes it should be this one:
[https://www.curseforge.com/minecraft/mc-mods/inventory-sorting](url)

**Comment by ejektaflex** [comment]
I've looked into this, and can replicate the issue. The problem is that Inventory Sorting does not seem to respect the `canInsert` and `canTakeItems` methods of those slots and moves items around willy-nilly without thinking about whether it *should* be able to move items around. This isn't a problem with Bountiful, but rather a consideration that Inventory Sorting needs to make.

I posted an issue to their issue tracker [here](https://github.com/kyrptonaught/Inventory-Sorter/issues/98).
