### ISSUE TITLE
[Bug]: Crash with BountyItem

### ISSUE THREAD

**Issue by RawrUniversal** [ejektaflex/Bountiful#286]
### What happened?

Crashed when clicking the bounty item. The Griefdefender dev said that it called "stack.getDisplayName()" when it crashes.

### Mod Version

6.0.3+1.20.1

### Mod Loader

Fabric

### Mod Loader Version

0.92.2+1.20.1

### Relevant log output

[crash-2024-06-07_07.09.00-server.txt](https://github.com/user-attachments/files/15746125/crash-2024-06-07_07.09.00-server.txt)

**Comment by ejektaflex** [comment]
Hi @RawrUniversal ! It seems like this is because we're doing a client server data pull on the server side. Base Minecraft has no reason to do this and quite frankly, most mods don't have any reason to do this either (Otherwise I would have received a bug report earlier, this code was committed 3.5 years ago according to [this](https://github.com/ejektaflex/Bountiful/commit/ce364e3fe0c9a47455bab88b68995471f98ee316#diff-590b97b2c8e969d25a8209ed58918d87f2b2c1f9b08b9237d90936133061a7a8)).

I will be fixing this, but only for an upcoming version and not for 1.20.1.
Thanks for the bug report!

**Comment by ejektaflex** [comment]
I fixed this on our side with 6.0.4-1.20.1. Just note that the GriefDefender dev should not be calling that code on the server-side, they have a bad sidedness issue that should probably be fixed on their end.
Thanks! :^)
