### ISSUE TITLE
[suggestion] bounties check for entity extensions

### ISSUE THREAD

**Issue by Jackiecrazy** [ejektaflex/Bountiful#41]
I took a bounty for 5 zombies, but killing extensions of zombies (specifically, the zombie varieties from special mobs) did not count towards the goal. It would be nice to have a method of counting any entity that extends a particular class for a bounty. It'd open up interesting options, such as "slay any 5 mobs" as a bounty requirement.

**Comment by ejektaflex** [comment]
That sounds great, though in code this can be done in two different ways: Either
* A) Extended the zombie class and creating a new mob with similar functionality
* B) Creating a whole new mob that looks like a zombie

I can catch instances when this is the case for scenario A, but it's impossible to know when a mod has been designed with scenario B. Furthermore, with scenario A, the modpack maker would probably still have to know the name of the mob's class (Which *does not* necessarily correlate with the mob, there is no 1:1 relation between mob classes and mobs), so you still cannot tell with any large degree of accuracy whether a mob is a variant of another mob (*Maybe* a Husk/Stray, but that's about it).

I wish I could do so reliably, though unfortunately it really depends on the code. Some current mods don't follow the correct practice and name their mobs correctly, which makes it so that they can't be recognized by Bountiful (or any other mods, for that matter). 

On the flip side, creating a "slay any 5 mobs" or "slay any 5 hostile/passive mobs" objective would be interesting, though I'm uncertain as to whether or not it's particularly engaging compared to how it is in it's current state.

**Comment by ejektaflex** [comment]
I've not gotten any feedback on how to implement this, and I can't seem to think of a solution that would work consistently, so I'm going to mark this as closed without a solution.
