### ISSUE TITLE
Potions come up as "uncraftable potion"

### ISSUE THREAD

**Issue by SilentGhost5** [ejektaflex/Bountiful#42]
I've tried to add potions as bounties but each time i specify a potion it comes up as "uncraftable potion" yet when i submit the right potion it still gives me back my bounty reward? Basically it works except that it says "uncraftable potion" so i don't know which potion I have to make. Even using the wiki's exact code causes this same problem.
"content": "minecraft:potion",
  "amount": {
    "min": 1,
    "max": 3
  },
  "unitWorth": 300,
  "weight": 100,
  "stages": ["a", "b"],
  "nbt_data": "{Potion: \"minecraft:healing\"}"

**Comment by ejektaflex** [comment]
You need to put a \ before every quote inside of your JSON quotation marks, otherwise it's not a valid JSON file.

So replace:

`"nbt_data": "{Potion: "minecraft:healing"}"`

With:

`"nbt_data": "{Potion: \"minecraft:healing\"}"`

The wiki does this as well, so you're obviously not using the exact same code as the wiki :^)

I hope that helps!

**Comment by ejektaflex** [comment]
Closing, never got a response and it's been well over two weeks
