### ISSUE TITLE
[Suggestion] Player killing bounties.

### ISSUE THREAD

**Issue by Xorbah** [ejektaflex/Bountiful#55]
Title. New type of bounties that generate an issued order to kill a player to retrieve the reward stated on the bounty.

**Comment by ejektaflex** [comment]
Hey, yeah, I have definitely thought about this before! I'd like to try this out sometime in the future for the next version of Bountiful. I'm going to keep this issue open as a feature request! However, not all games feature PvP so I would keep it off by default.

A few questions that I'm going to throw out there:
* Would the player's names show up on the bounty in the bounty board? Would you be able to choose between two player bounties based on who they are for? If so, what if you saw your own bounty on the bounty board? How would you handle that, or would it be better to assign you a random player once you took the bounty?
* What if you have a bounty for, say, Player X, and then Player X logs off? Should the bounty automatically expire? Should it switch to a different player?
* How is the worth of a player bounty determined? Is it determined based on the player's experience level at the time when you take the bounty? That seems like the best solution.

This brings up another idea: What if we had bounties with a mystery reward? It would be cool to hide some rewards and only show a "???" instead.

I'd love feedback from anyone and everyone about what they think before I think about implementing this for a future version. Thank you!

**Comment by CalaMariGold** [comment]
Hi there! Lead dev for Rebirth of the Night here, and loving this mod. I can add my input to these questions.

Player bounties should assign as soon as it's generated, not on pick up. I think there is a certain appeal in seeing your own name in the bounties. It will make you be on the look out for other players. You would not be able to complete it. (bonus if you can't even pick up your own bounty)

The bounty shouldn't expire when the player logs off. This would prevent players from relogging just to expire the bounty. It should stay up no matter what until the time runs out.

The worth can be based on experience, but if you could also base it on their armor and armor toughness, that would be a plus.

As far as mystery rewards, this sounds great. It should be an option in the config, and you can set how often bounties are mysteries, from all of the bounties to none of them.


Hope you take into consideration these ideas! Let me know if you need anything else.

**Comment by ejektaflex** [comment]
Hey thanks @CalaMariGold ! I've been busy with other stuff, but if/when I get around to this, this sounds like a great approach.

**Comment by Jophire** [comment]
Been thinking about this recently myself. Some ideas:

In General:
Bounties only ticks down while the player is online.
If two or more players grab a bounty for the same target, as soon as the target dies, all other bounties for that target that are currently active expire. This way you don't have a guy getting killed repeatedly due to bad rng.

For randomly generated:
Bounty value is based off player score.
If more then one bounty for a given player is generated, use the remaining time of the oldest bounty.

For command generated:
These are separate from randomly generated bounties and should not impact normal bounty limits. Maybe a new Wanted Board block?
Bounty bag: Small craftable storage bag(3-4 slots?), which when held and using a "/bo create playername duration" gets consumed, setting the bounties rewards. (Some sort of balance check? config option for who can use?)
Bounties generated this way should show up in every bounty board, and regen every couple of board openings until the bounty expires.

**Comment by ovfudj** [comment]
As long as you are doing multiplayer requirements for player assassination's, it might be also worth considering a bounty for successfully protecting a player for a time limit, and maybe even other entities.

**Comment by ejektaflex** [comment]
In 1.19.4+, you can create either an entity objective with content of `minecraft:player`, or a Criteria reward that would target a player with a specific name. You can read more about it here:
https://kambrik.ejekta.io/mods/bountiful/

It's not as powerful as you're thinking, but it works.
