### ISSUE TITLE
[Bug] Bounty time does not decrease when placed in chest/backpack/container

### ISSUE THREAD

**Issue by abboip** [ejektaflex/Bountiful#6]
A bounty placed in a chest or a backpack (eg. one from Leather Works) does not decrease in time. 

(Edit: Logging off also doesn't decrease the time -- but that's probably more fair than depositing it into a chest.)

Perhaps if it can't be tracked while in another inventory, it could note the server time it was deposited and subtract the time allotted when withdrawn?

**Comment by ejektaflex** [comment]
This is a valid point. For the next version, I'm going to switch to making it so that bounties are not removed when the time limit is reached, so instead they will say "Expired" where the time remaining used to be. 

Then, I will have it update the time remaining whenever you try use the item and whenever you hover over it, so that during critical times it will still be up to date and given valid results, irregardless of how much time has passed.

**Comment by ejektaflex** [comment]
Implemented in 8014740, bounties should now compute their expiry time based on the time that the bounty was taken and the time given to complete the bounty. Therefore, it should work in any container without needing to be updated.
