### ISSUE TITLE
Generation Conflict with Waystones Mod

### ISSUE THREAD

**Issue by MLMII** [ejektaflex/Bountiful#68]
- Forge version:  1.15.2-31.1.25
- Bountiful version: 3.0.0-1.15.2
- Other mods: Waystones 1.15.2-6.0.1

Bounty Boards do not generate when Waystones are set to generate in villages, but with that feature turned off Bounty Boards do generate.  It tested this on two different worlds using the same seed.

 I'll also post this issue on the Waystone page as well.

Thanks,

**Comment by ejektaflex** [comment]
Yep, that is definitely a bug. It's because I couldn't find any resources for village generation in 1.14/1.15, and the eventual solution that I found was really janky. It looks like I can use Blay's code there as an example for how this *should* be done, so this helps me a lot. I'll add it to the list for v3.1.0.

**Comment by ejektaflex** [comment]
Yeah, so it looks like Blay's code and mine both are quite janky and will interfere with each other, since Forge doesn't have proper support for adding/removing village Jigsaw pieces (see: https://github.com/blay09/Waystones/issues/219). Unfortunately, there's nothing that either of us can do about it right now until Forge merges in a pull request (see https://github.com/MinecraftForge/MinecraftForge/pull/6324) for 1.14 & 1.15. I'm going to close this for now because as far as I know there's nothing more that I (or Blay) can do about it, but I'll watch that PR in case there's any updates so that I can fix it.
