### ISSUE TITLE
Can't Craft Bounty Board

### ISSUE THREAD

**Issue by Toderra** [ejektaflex/Bountiful#75]
![not working](https://user-images.githubusercontent.com/51772036/78934176-7670f580-7a78-11ea-9d4f-138e99da7eef.png)

As the title states, I cannot craft the bounty board for some reason. Other mods I have installed that could be interfering: Explorercraft, Harvest, Industrial Foregoing, JEI, and Useful Backpacks (along with Kottle Library, Titanium, and U Team Core)

**Comment by ejektaflex** [comment]
@Toderra Please conform to the [GitHub issue template](https://github.com/ejektaflex/Bountiful/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md) so that I have all the information necessary to see what's happening. I don't know the version of Minecraft, nor Forge, nor the mod so it could be a plethora of things :^)

It seems like Minecraft v1.14.x/1.15.x. Depending on your version, it might be craftable or it might not (I added the recipe in Bountiful 3.1). It's different from the 1.12 one (It uses a diamond - bounty boards should be rare enough that it's harder to own more than one)

**Comment by ejektaflex** [comment]
I messed up the Stale bot, oops,  but I've fixed that. I'm closing this issue because it's not had any recent activity. It sounded like you weren't using the latest release version of the mod, but I can't be sure without any more information. Feel free to reopen the issue if you have any more information.
