### ISSUE TITLE
Placing Bounty Boards with "Global Bounty Inventory" enabled generates new bounties

### ISSUE THREAD

**Issue by NotMyWing** [ejektaflex/Bountiful#81]
## Bug Report

**Observed Behaviour**

When `B:"Global Bounty Inventory"` is set to `true`, repeatedly placing Bounty Boards fills the global bounty inventory with new bounties.

https://i.neeve.co/FondMatureEarthworm.mp4

**Minimal setup needed to reproduce**

- Forge version: 14.23.5.2854
- Bountiful version: 2.2.2

**Steps to reproduce**

1. Set `B:"Global Bounty Inventory"` to `true`
2. Start the game
3. Load into a single player world or join a server
4. Put a Bounty Board down and right-click to see the contents

Repeat 4 until the global inventory is filled with bounties.

**Comment by ejektaflex** [comment]
Ah, yeah, this makes sense. While it is a bug, and I do small bits of maintenance on the 1.12 version when necessary, this doesn't cause a crash so I don't think that I am going to fix it. I've mostly moved on with development on the 1.14/1.15 versions of the mod, which is greatly improved and much easier to maintain. If you're playing on a server, I'd recommend changing the config so that the board is not breakable or craftable anymore (as the entire reason why that option exists is so that you can't abuse crafting/owning a ton of bounty boards).

If you can find someone willing to do a PR for this issue, I would accept it!
