### ISSUE TITLE
[Suggestion] Next Bounty In... Countdown

### ISSUE THREAD

**Issue by abboip** [ejektaflex/Bountiful#9]
Another suggestion I saw on curseforge involved being able to start bounty boards with 0 bounties -- but that might be confusing for new players. A way to alleviate that (and give the player more information) would be to include a countdown to the next bounty in the bounty board inventory container somewhere.

**Comment by ejektaflex** [comment]
This is a great idea. I actually had another suggestion, though, which was that if you right click on the block and there are no bounties, instead of opening the gui it will send to the chat "No bounties available, come back later!". 

This method indicates that the board *is* empty, but that it is indeed working and that they should check back at a later date.

**Comment by ejektaflex** [comment]
Expired bounties have been implemented in v2.0 as of f991b93
