### ISSUE TITLE
Village Config Doesn't Reduce Board Numbers

### ISSUE THREAD

**Issue by MokahTGS** [ejektaflex/Bountiful#95]
## Bug Report

Changing the bounty board numbers that are supposed to spawn in villages doesn't seem to do anything.  I'm trying to reduce the amount to exactly 1 board per village, but no matter what is in the configs, it spawns several...sometimes up to five.

- Forge version: Bountiful-1.15.2-3.1.2.jar
- Bountiful version: Bountiful-1.15.2-3.1.2.jar

**Comment by ejektaflex** [comment]
You can't reduce the amount to exactly 1 board per village. If it was possible, I'd have totally done so!

Here's why, this is how village generation works:

All village pieces fit together like a Jigsaw puzzle. The town center, with the bell, acts as the middle. It then builds out roads *randomly* in all directions. On the sides of the roads it places houses and other decorations *at random*. This is all random, it picks different pieces from different pools at random and just plops them down.

That being said, you can no longer guarantee that a structure piece will get picked for village generation. I've added my Bounty Board to the housing pool, and it has a chance to spawn in place of a house. That means, that the higher that value is, the greater the chance that a board spawns instead of a house. So, if the number is too high, all houses suddenly become bounty boards. If the number is too low, only houses spawn and no boards spawn.

Given the random procedural nature of the village generation system in 1.13+, there is *no way* that I can guarantee that a bounty board generates in villages. I can only change the weight concerning roughly how often they show up compared to village housing. Hence, it can give a rough average but the actual number of placed bounty boards is completely up to chance. Also: Forge has not included a way of officially adding to these generation pools, so I have to do some hacky stuff to get it to even work. I wish it weren't so.
